language: go
go_import_path: github.com/ringcentral/engage-api-docs
go:
  - "1.15.x"
  - "1.14.x"
  - "1.13.x"
  - master
matrix:
  allow_failures:
    - go: master
install:
  - go get -t -v ./...
script:
  - go test -v ./...
