site_name: RingCentral Engage Developer Guide
site_url: https://engage-api-docs.rtfd.org
site_favicon: favicon.ico
repo_url: https://github.com/ringcentral/engage-digital-api-docs
docs_dir: docs
theme:
  name: ringcentral
  product_section: engage
  fluid_layout: True
  suppress_nextprev: true
  shortcuts:
    - foo

plugins:
  - git-committers:
      repository: ringcentral/engage-digital-api-docs
      branch: master
  - bootstrap-tables

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - codehilite:
      linenums: "None"

#extra_css: [extra.css]
#extra_javascript: [fonts.js]
pages:
- 'Primary':
  - 'Interactions':
    - 'Overview': digital/interactions/index.md
    - 'Getting Started':
      - 'Node JS': digital/interactions/quick-start/node.md
      - 'PHP': digital/interactions/quick-start/php.md
      - 'Python': digital/interactions/quick-start/python.md
      - 'Ruby': digital/interactions/quick-start/ruby.md
    - 'Chatbots':
      - 'Overview': digital/interactions/chatbots/overview.md
      - 'Implementation': digital/interactions/chatbots/implementation.md
      - 'Replying to Messages': digital/interactions/chatbots/replies.md
      - 'Creating Interventions': digital/interactions/chatbots/interventions.md
      - 'Transferring to an Agent': digital/interactions/chatbots/transfers.md
      - 'Closing Threads': digital/interactions/chatbots/threads.md
  - 'Routing':
    - 'Overview': digital/routing/index.md
    - 'Getting Started':
      - 'Node JS': digital/routing/quick-start/node.md
      - 'PHP': digital/routing/quick-start/php.md
      - 'Python': digital/routing/quick-start/python.md
      - 'Ruby': digital/routing/quick-start/ruby.md
- 'Secondary':
  - 'Using the API':
    - 'Obtain an Access Token': digital/basics/access-token.md
    - 'Requests': digital/basics/requests.md
    - 'Responses and Errors': digital/basics/responses.md
    - 'Authentication': digital/basics/auth.md
    - 'Uploading Files': digital/basics/uploads.md
    - 'Filters and Pagination': digital/basics/pagination.md
    - 'User Impersonation': digital/basics/impersonation.md
  - 'Events and Notifications':
    - 'Overview': digital/webhooks/index.md
    - 'Creating Webhooks': digital/webhooks/create.md
    - 'Receiving Events': digital/webhooks/receive.md
    - 'Event Types': digital/webhooks/events.md
  - 'SDKs': digital/sdks.md
  - 'Postman': digital/postman.md